DROP TABLE IF EXISTS users, requests, items, bookings, comments;

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
  request_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  description VARCHAR(512) NOT NULL,
  requestor_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
  create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
  item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) NOT NULL,
  available BOOLEAN,
  owner_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
  request_id BIGINT REFERENCES requests (request_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  booking_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
  start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id BIGINT NOT NULL REFERENCES items (item_id) ON DELETE CASCADE,
  booking_status varchar(8)
);

CREATE TABLE IF NOT EXISTS comments (
  comment_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  text VARCHAR(2000) NOT NULL,
  item_id BIGINT NOT NULL REFERENCES items (item_id) ON DELETE CASCADE,
  author_id BIGINT NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
  create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);